### ISSUE TITLE
Failed to execute "bundle exec rake vcr:rerecord"

### ISSUE THREAD

**Issue by Yikun** [ManageIQ/manageiq-providers-openstack#478]
The script to run looks like:
```
bin/setup
bundle install
bundle exec rake evm:db:reset db:seed
bundle exec rails r spec/tools/environment_builders/openstack.rb
bundle exec rake vcr:rerecord
```

The complete running script in [1]
[1] https://github.com/liu-sheng/openlab-zuul-jobs/blob/master/playbooks/manageiq-providers-openstack-test-devstack/run.yaml#L91-L109

But when the `bundle exec rake vcr:rerecord` is excuted, we got the below error

```
Loading enviroment credentials for liberty_keystone_v3
** ManageIQ master, codename: Ivanchuk
The HashDiff constant used by this gem conflicts with another gem of a similar name.  As of version 1.0 the HashDiff constant will be completely removed and replaced by Hashdiff.  For more information see https://github.com/liufengyun/hashdiff/issues/45.
** ManageIQ master, codename: Ivanchuk

An error occurred while loading spec_helper.
Failure/Error: rec = find_by(:name => t[:name])

ActiveRecord::StatementInvalid:
  PG::UndefinedTable: ERROR:  relation "notification_types" does not exist
  LINE 8:                WHERE a.attrelid = '"notification_types"'::re...
                                            ^
  :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                       pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
               (SELECT c.collname FROM pg_collation c, pg_type t
                 WHERE c.oid = a.attcollation AND t.oid = a.atttypid AND a.attcollation <> t.typcollation),
                       col_description(a.attrelid, a.attnum) AS comment
                  FROM pg_attribute a LEFT JOIN pg_attrdef d
                    ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                 WHERE a.attrelid = '"notification_types"'::regclass
                   AND a.attnum > 0 AND NOT a.attisdropped
                 ORDER BY a.attnum
# ./spec/manageiq/app/models/notification_type.rb:50:in `block in seed'
# ./spec/manageiq/app/models/notification_type.rb:49:in `each'
# ./spec/manageiq/app/models/notification_type.rb:49:in `seed'
# ------------------
# --- Caused by: ---
# PG::UndefinedTable:
#   ERROR:  relation "notification_types" does not exist
#   LINE 8:                WHERE a.attrelid = '"notification_types"'::re...
#                                             ^
#   ./spec/manageiq/app/models/notification_type.rb:50:in `block in seed'
Run options: include {:providers_common=>true}
```

The completed log can be found in [2]
[2] http://80.158.17.129/logs/3/3/d648c4346575274497091916445f23036b683ee4/check/manageiq-providers-openstack-test-devstack/f1ce46a/job-output.txt.gz

Not sure how to address this problem? Any idea on it?

**Comment by agrare** [comment]
@Yikun if you reset the db you also have to reset the test db, `bin/setup` and `bin/update` do this for you but anything you do `rake evm:db:reset db:seed` you also have to do `rake test:vmdb:setup`

**Comment by Fryguy** [comment]
Closing as the question has been answered.  Please reopen if you are still seeing an issue.
