### ISSUE TITLE
openstack provider failed to do status update

### ISSUE THREAD

**Issue by tjyang** [ManageIQ/manageiq-providers-openstack#70]
* On our miq02 which is running latest code from master. The openstack provider failed to do status refresh. The connected openstack is Ubuntu openstack added as Cloud provider.
* Same openstack farm connected to Fine-2 miq fine without refresh issue.

```
[root@miq02 vmdb]# git log |head
commit b4554f7ed13368e6985d993ca8066d12a02d03a3
Merge: 56f639e 750d3c4
Author: Jason Frey <fryguy9@gmail.com>
Date:   Tue Jul 25 22:23:26 2017 -0400

    Merge pull request #15393 from zeari/unify_container_definition

    Merge container_definition and container

commit 56f639e6ed4f8e2fcef1f52e51466f891bf7305c
[root@miq02 vmdb]#
```
* Screenshot

![image](https://user-images.githubusercontent.com/378638/28637426-16e8ea9a-7207-11e7-8a77-533c4a9dd8a9.png)

*  EVM Log file around the error message.
```
<snipped>
[----] E, [2017-07-26T14:15:36.192110 #5857:c6f138] ERROR -- : MIQ(ManageIQ::Providers::Openstack::CloudManager::Refresher#refresh) EMS: [OpenStack_POC], id: [15] Refresh failed
[----] E, [2017-07-26T14:15:36.192385 #5857:c6f138] ERROR -- : [ActiveRecord::AssociationTypeMismatch]: Host(#118366160) expected, got NilClass(#13131780)  Method:[block in method_missing]
[----] E, [2017-07-26T14:15:36.192494 #5857:c6f138] ERROR -- : /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.4/lib/active_record/associations/association.rb:231:in `raise_on_type_mismatch!'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.4/lib/active_record/associations/collection_association.rb:382:in `block in replace'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.4/lib/active_record/associations/collection_association.rb:382:in `each'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.4/lib/active_record/associations/collection_association.rb:382:in `replace'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.4/lib/active_record/associations/collection_association.rb:48:in `writer'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.4/lib/active_record/associations/builder/association.rb:119:in `hosts='
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activemodel-5.0.4/lib/active_model/attribute_assignment.rb:46:in `public_send'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activemodel-5.0.4/lib/active_model/attribute_assignment.rb:46:in `_assign_attribute'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activemodel-5.0.4/lib/active_model/attribute_assignment.rb:40:in `block in _assign_attributes'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activemodel-5.0.4/lib/active_model/attribute_assignment.rb:39:in `each'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activemodel-5.0.4/lib/active_model/attribute_assignment.rb:39:in `_assign_attributes'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.4/lib/active_record/attribute_assignment.rb:26:in `_assign_attributes'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activemodel-5.0.4/lib/active_model/attribute_assignment.rb:33:in `assign_attributes'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.4/lib/active_record/core.rb:319:in `initialize'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.4/lib/active_record/inheritance.rb:65:in `new'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.4/lib/active_record/inheritance.rb:65:in `new'
/var/www/miq/vmdb/app/models/mixins/new_with_type_sti_mixin.rb:16:in `new'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.4/lib/active_record/persistence.rb:50:in `create!'
/var/www/miq/vmdb/app/models/manager_refresh/save_collection/saver/default.rb:17:in `create_record!'
/var/www/miq/vmdb/app/models/manager_refresh/save_collection/saver/base.rb:80:in `block (2 levels) in save!'
/var/www/miq/vmdb/app/models/manager_refresh/save_collection/saver/base.rb:77:in `each'
/var/www/miq/vmdb/app/models/manager_refresh/save_collection/saver/base.rb:77:in `block in save!'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.4/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.4/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.4/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.4/lib/active_record/transactions.rb:211:in `transaction'
/var/www/miq/vmdb/app/models/manager_refresh/save_collection/saver/base.rb:76:in `save!'
/var/www/miq/vmdb/app/models/manager_refresh/save_collection/saver/base.rb:29:in `save_inventory_collection!'
/var/www/miq/vmdb/app/models/manager_refresh/save_collection/base.rb:22:in `save_inventory'
/var/www/miq/vmdb/app/models/manager_refresh/save_collection/base.rb:12:in `save_inventory_object_inventory'
/var/www/miq/vmdb/app/models/manager_refresh/save_collection/topological_sort.rb:23:in `block (2 levels) in save_collections'
/var/www/miq/vmdb/app/models/manager_refresh/save_collection/topological_sort.rb:22:in `each'
/var/www/miq/vmdb/app/models/manager_refresh/save_collection/topological_sort.rb:22:in `block in save_collections'
/var/www/miq/vmdb/app/models/manager_refresh/save_collection/topological_sort.rb:20:in `each'
/var/www/miq/vmdb/app/models/manager_refresh/save_collection/topological_sort.rb:20:in `each_with_index'
/var/www/miq/vmdb/app/models/manager_refresh/save_collection/topological_sort.rb:20:in `save_collections'
/var/www/miq/vmdb/app/models/manager_refresh/save_inventory.rb:15:in `save_inventory'
/var/www/miq/vmdb/app/models/ems_refresh/save_inventory.rb:4:in `save_ems_inventory'
/var/www/miq/vmdb/app/models/ems_refresh/refreshers/ems_refresher_mixin.rb:152:in `save_inventory'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-providers-openstack-bed81b7bd712/app/models/manageiq/providers/openstack/cloud_manager/refresher.rb:12:in `save_inventory'
/var/www/miq/vmdb/app/models/ems_refresh/refreshers/ems_refresher_mixin.rb:91:in `block in refresh_targets_for_ems'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-gems-pending-6bdd64449485/lib/gems/pending/util/extensions/miq-benchmark.rb:11:in `realtime_store'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-gems-pending-6bdd64449485/lib/gems/pending/util/extensions/miq-benchmark.rb:30:in `realtime_block'
/var/www/miq/vmdb/app/models/ems_refresh/refreshers/ems_refresher_mixin.rb:91:in `refresh_targets_for_ems'
/var/www/miq/vmdb/app/models/ems_refresh/refreshers/ems_refresher_mixin.rb:24:in `block (2 levels) in refresh'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-gems-pending-6bdd64449485/lib/gems/pending/util/extensions/miq-benchmark.rb:11:in `realtime_store'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-gems-pending-6bdd64449485/lib/gems/pending/util/extensions/miq-benchmark.rb:30:in `realtime_block'
/var/www/miq/vmdb/app/models/ems_refresh/refreshers/ems_refresher_mixin.rb:24:in `block in refresh'
/var/www/miq/vmdb/app/models/ems_refresh/refreshers/ems_refresher_mixin.rb:14:in `each'
/var/www/miq/vmdb/app/models/ems_refresh/refreshers/ems_refresher_mixin.rb:14:in `refresh'
/var/www/miq/vmdb/app/models/manageiq/providers/base_manager/refresher.rb:9:in `refresh'
/var/www/miq/vmdb/app/models/ems_refresh.rb:97:in `block in refresh'
/var/www/miq/vmdb/app/models/ems_refresh.rb:96:in `each'
/var/www/miq/vmdb/app/models/ems_refresh.rb:96:in `refresh'
/var/www/miq/vmdb/app/models/miq_queue.rb:387:in `block in deliver'
/opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
/opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/var/www/miq/vmdb/app/models/miq_queue.rb:386:in `deliver'
/var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb:109:in `deliver_queue_message'
/var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb:138:in `deliver_message'
/var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb:156:in `block in do_work'
/var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb:150:in `loop'
/var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb:150:in `do_work'
/var/www/miq/vmdb/app/models/miq_worker/runner.rb:341:in `block in do_work_loop'
/var/www/miq/vmdb/app/models/miq_worker/runner.rb:338:in `loop'
/var/www/miq/vmdb/app/models/miq_worker/runner.rb:338:in `do_work_loop'
/var/www/miq/vmdb/app/models/miq_worker/runner.rb:160:in `run'
/var/www/miq/vmdb/app/models/miq_worker/runner.rb:134:in `start'
/var/www/miq/vmdb/app/models/miq_worker/runner.rb:22:in `start_worker'
/var/www/miq/vmdb/app/models/miq_worker.rb:357:in `block in start_runner_via_fork'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/nakayoshi_fork-0.0.3/lib/nakayoshi_fork.rb:24:in `fork'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/nakayoshi_fork-0.0.3/lib/nakayoshi_fork.rb:24:in `fork'
/var/www/miq/vmdb/app/models/miq_worker.rb:355:in `start_runner_via_fork'
/var/www/miq/vmdb/app/models/miq_worker.rb:349:in `start_runner'
/var/www/miq/vmdb/app/models/miq_worker.rb:383:in `start'
/var/www/miq/vmdb/app/models/miq_worker.rb:274:in `start_worker'
/var/www/miq/vmdb/app/models/mixins/per_ems_worker_mixin.rb:68:in `start_worker_for_ems'
/var/www/miq/vmdb/app/models/mixins/per_ems_worker_mixin.rb:46:in `block in sync_workers'
/var/www/miq/vmdb/app/models/mixins/per_ems_worker_mixin.rb:45:in `each'
/var/www/miq/vmdb/app/models/mixins/per_ems_worker_mixin.rb:45:in `sync_workers'
/var/www/miq/vmdb/app/models/miq_server/worker_management/monitor.rb:53:in `block in sync_workers'
/var/www/miq/vmdb/app/models/miq_server/worker_management/monitor.rb:50:in `each'
/var/www/miq/vmdb/app/models/miq_server/worker_management/monitor.rb:50:in `sync_workers'
/var/www/miq/vmdb/app/models/miq_server/worker_management/monitor.rb:22:in `monitor_workers'
/var/www/miq/vmdb/app/models/miq_server.rb:346:in `block in monitor'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-gems-pending-6bdd64449485/lib/gems/pending/util/extensions/miq-benchmark.rb:11:in `realtime_store'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-gems-pending-6bdd64449485/lib/gems/pending/util/extensions/miq-benchmark.rb:30:in `realtime_block'
/var/www/miq/vmdb/app/models/miq_server.rb:346:in `monitor'
/var/www/miq/vmdb/app/models/miq_server.rb:368:in `block (2 levels) in monitor_loop'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-gems-pending-6bdd64449485/lib/gems/pending/util/extensions/miq-benchmark.rb:11:in `realtime_store'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-gems-pending-6bdd64449485/lib/gems/pending/util/extensions/miq-benchmark.rb:30:in `realtime_block'
/var/www/miq/vmdb/app/models/miq_server.rb:368:in `block in monitor_loop'
/var/www/miq/vmdb/app/models/miq_server.rb:367:in `loop'
/var/www/miq/vmdb/app/models/miq_server.rb:367:in `monitor_loop'
/var/www/miq/vmdb/app/models/miq_server.rb:250:in `start'
/var/www/miq/vmdb/lib/workers/evm_server.rb:27:in `start'
/var/www/miq/vmdb/lib/workers/evm_server.rb:48:in `start'
/var/www/miq/vmdb/lib/workers/bin/evm_server.rb:4:in `<main>'
[----] E, [2017-07-26T14:15:36.192577 #5857:c6f138] ERROR -- : MIQ(ManageIQ::Providers::Openstack::CloudManager::Refresher#refresh) EMS: [OpenStack_POC], id: [15] Unable to perform refresh for the following targets:
[----] E, [2017-07-26T14:15:36.192717 #5857:c6f138] ERROR -- : MIQ(ManageIQ::Providers::Openstack::CloudManager::Refresher#refresh)  --- ManageIQ::Providers::Openstack::CloudManager [OpenStack_POC] id [15]
[----] E, [2017-07-26T14:15:36.255869 #5857:c6f138] ERROR -- : MIQ(MiqQueue#deliver) Message id: [61802], Error: [Host(#118366160) expected, got NilClass(#13131780)]
[----] E, [2017-07-26T14:15:36.256064 #5857:c6f138] ERROR -- : [EmsRefresh::Refreshers::EmsRefresherMixin::PartialRefreshError]: Host(#118366160) expected, got NilClass(#13131780)  Method:[block in method_missing]
[----] E, [2017-07-26T14:15:36.256208 #5857:c6f138] ERROR -- : /var/www/miq/vmdb/app/models/ems_refresh/refreshers/ems_refresher_mixin.rb:50:in `refresh'
/var/www/miq/vmdb/app/models/manageiq/providers/base_manager/refresher.rb:9:in `refresh'
/var/www/miq/vmdb/app/models/ems_refresh.rb:97:in `block in refresh'
/var/www/miq/vmdb/app/models/ems_refresh.rb:96:in `each'
/var/www/miq/vmdb/app/models/ems_refresh.rb:96:in `refresh'
/var/www/miq/vmdb/app/models/miq_queue.rb:387:in `block in deliver'
/opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
/opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/var/www/miq/vmdb/app/models/miq_queue.rb:386:in `deliver'
/var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb:109:in `deliver_queue_message'
/var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb:138:in `deliver_message'
/var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb:156:in `block in do_work'
/var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb:150:in `loop'
/var/www/miq/vmdb/app/models/miq_queue_worker_base/runner.rb:150:in `do_work'
/var/www/miq/vmdb/app/models/miq_worker/runner.rb:341:in `block in do_work_loop'
/var/www/miq/vmdb/app/models/miq_worker/runner.rb:338:in `loop'
/var/www/miq/vmdb/app/models/miq_worker/runner.rb:338:in `do_work_loop'
/var/www/miq/vmdb/app/models/miq_worker/runner.rb:160:in `run'
/var/www/miq/vmdb/app/models/miq_worker/runner.rb:134:in `start'
/var/www/miq/vmdb/app/models/miq_worker/runner.rb:22:in `start_worker'
/var/www/miq/vmdb/app/models/miq_worker.rb:357:in `block in start_runner_via_fork'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/nakayoshi_fork-0.0.3/lib/nakayoshi_fork.rb:24:in `fork'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/nakayoshi_fork-0.0.3/lib/nakayoshi_fork.rb:24:in `fork'
/var/www/miq/vmdb/app/models/miq_worker.rb:355:in `start_runner_via_fork'
/var/www/miq/vmdb/app/models/miq_worker.rb:349:in `start_runner'
/var/www/miq/vmdb/app/models/miq_worker.rb:383:in `start'
/var/www/miq/vmdb/app/models/miq_worker.rb:274:in `start_worker'
/var/www/miq/vmdb/app/models/mixins/per_ems_worker_mixin.rb:68:in `start_worker_for_ems'
/var/www/miq/vmdb/app/models/mixins/per_ems_worker_mixin.rb:46:in `block in sync_workers'
/var/www/miq/vmdb/app/models/mixins/per_ems_worker_mixin.rb:45:in `each'
/var/www/miq/vmdb/app/models/mixins/per_ems_worker_mixin.rb:45:in `sync_workers'
/var/www/miq/vmdb/app/models/miq_server/worker_management/monitor.rb:53:in `block in sync_workers'
/var/www/miq/vmdb/app/models/miq_server/worker_management/monitor.rb:50:in `each'
/var/www/miq/vmdb/app/models/miq_server/worker_management/monitor.rb:50:in `sync_workers'
/var/www/miq/vmdb/app/models/miq_server/worker_management/monitor.rb:22:in `monitor_workers'
/var/www/miq/vmdb/app/models/miq_server.rb:346:in `block in monitor'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-gems-pending-6bdd64449485/lib/gems/pending/util/extensions/miq-benchmark.rb:11:in `realtime_store'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-gems-pending-6bdd64449485/lib/gems/pending/util/extensions/miq-benchmark.rb:30:in `realtime_block'
/var/www/miq/vmdb/app/models/miq_server.rb:346:in `monitor'
/var/www/miq/vmdb/app/models/miq_server.rb:368:in `block (2 levels) in monitor_loop'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-gems-pending-6bdd64449485/lib/gems/pending/util/extensions/miq-benchmark.rb:11:in `realtime_store'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/manageiq-gems-pending-6bdd64449485/lib/gems/pending/util/extensions/miq-benchmark.rb:30:in `realtime_block'
/var/www/miq/vmdb/app/models/miq_server.rb:368:in `block in monitor_loop'
/var/www/miq/vmdb/app/models/miq_server.rb:367:in `loop'
/var/www/miq/vmdb/app/models/miq_server.rb:367:in `monitor_loop'
/var/www/miq/vmdb/app/models/miq_server.rb:250:in `start'
/var/www/miq/vmdb/lib/workers/evm_server.rb:27:in `start'
/var/www/miq/vmdb/lib/workers/evm_server.rb:48:in `start'
/var/www/miq/vmdb/lib/workers/bin/evm_server.rb:4:in `<main>'
NOTICE:  identifier "MIQ|13743|1|1247|1|StorageManager::CinderManager::EventCatche..." will be truncated to "MIQ|13743|1|1247|1|StorageManager::CinderManager::EventCatche.."
/var/www/miq/vmdb/app/models/manageiq/providers/base_manager/event_catcher/runner.rb:120:in `monitor_events': must be implemented in subclass (NotImplementedError)
        from /var/www/miq/vmdb/app/models/manageiq/providers/base_manager/event_catcher/runner.rb:162:in `block in start_event_monitor'

<snipped>

```

**Comment by tzumainn** [comment]
Would it be possible to get the full evm.log somewhere?

Is this just an openstack cloud provider, or is there also an openstack infra provider? I'm curious because a cloud provider shouldn't read Hosts otherwise.

**Comment by tjyang** [comment]
@tzumainn , Thanks for the response. Please see my updated post with info you requested.

**Comment by tzumainn** [comment]
@Ladas Judging from the stack trace, I'm not sure this is actually touching the meat of the openstack provider code - could this be an issue with the core refresh code?

**Comment by Ladas** [comment]
@tjyang just little above in the log, there should be an info about what we are trying to save, that should help to figure out what is wrong

**Comment by Ladas** [comment]
@tzumainn @tjyang I think the issue might be here https://github.com/Ladas/manageiq-providers-openstack/blob/cf63d41eb0dd5a0d3f94e92325527ad2db02926e/app/models/manageiq/providers/openstack/inventory/parser/cloud_manager.rb#L109

That rails doesn't like if one of the hosts is nil (same as it should receive uniq list). It should be:

```ruby
host_aggregate.hosts = hosts.compact.uniq
```

you can try in rails c, that host_aggregate.hosts = [host, nil], throws the same error

**Comment by tzumainn** [comment]
@Ladas Thanks! Fix merged.@tjyang can you update your master checkout and try again?

**Comment by tjyang** [comment]
@tzumainn , I will try the one-liner fix.

**Comment by tjyang** [comment]
@tzumainn 
* on my miq02 instance using master branch. I am using following commands to sync with master's frequent changes. 

```
vmdb && systemctl  stop evmserverd && git pull && bin/update && reboot
```

* From output of "bin/update", it  is pulling down openstack provider source as shown below.

```
<snipped>
Already up-to-date.
== Installing dependencies ==
Fetching https://github.com/ManageIQ/manageiq-gems-pending.git
Fetching https://github.com/ManageIQ/handsoap.git
Fetching https://github.com/ManageIQ/manageiq-providers-ansible_tower
Fetching https://github.com/ManageIQ/manageiq-schema
<snipped>
Fetching https://github.com/ManageIQ/manageiq-providers-openstack
<snipped>
```

*  bin/update command seems work the magic to bring down the one-liner fix.  My O.S. Icon is now alive with correct numeric numbers. 

![image](https://user-images.githubusercontent.com/378638/28672585-bae533f8-72a5-11e7-9ca1-b4255db8640a.png)

**Comment by tzumainn** [comment]
Great! @Ladas thanks again for the fix!

**Comment by tjyang** [comment]
Thanks to @tzumainn and @Ladas for the quick responses and fix.
